### ISSUE TITLE
Question about connected glass textures

### ISSUE THREAD

**Issue by JMoVS** [FaithfulTeam/Faithful#1]
Hi, loving your work on the texture pack. Such an awesome texture pack!

I have connected (!) _clear_ glass textures for all colors. Are you interested in integrating them or do you want to stick to the default non-clear look? I could give you the folder as is (was a pain to export all the 40 something images per color).

Also, do you know whether minecraft 1.12 also changes the colors of the glass? I'm not finding any information on that.

**Comment by xMrVizzy** [comment]
I don't know about new colors of glass, but it would be great. Clear glass it's cool, but not a Faithful style, it prefer Vanila look, you can make a Addon for it!

**Comment by JMoVS** [comment]
How would I go about doing an "addon" for that? Could you do that? I'd just give you the glass textures and you could do that? I'm not registered with the usual sites anywhere...

**Comment by Iglu47** [comment]
https://github.com/FaithfulTeam/Faithful/tree/master/assets/minecraft/mcpatcher/ctm/glass_stained

**Comment by Iglu47** [comment]
Texture | 1.7.10 | 1.8.9 | 1.9.4 | 1.10.2 | 1.11.2
------------------------- | -------- | -------- | -------- | -------- | --------
glass | 251D7C23 | 251D7C23 | 251D7C23 | 251D7C23 | 251D7C23
glass_black | 97572AAE | 97572AAE | A484B493 | A484B493 | A484B493
glass_blue | C8AF1F99 | C8AF1F99 | 9F97E1F2 | 9F97E1F2 | 9F97E1F2
glass_brown | FC1ECE96 | FC1ECE96 | CB501C5D | CB501C5D | CB501C5D
glass_cyan | 0719F191 | 0719F191 | 60196651 | 60196651 | 60196651
glass_gray | E50673EE | E50673EE | C460F49F | C460F49F | C460F49F
glass_green | 33CD017E | 33CD017E | 8AC1E490 | 8AC1E490 | 8AC1E490
glass_light_blue | 2983B949 | 2983B949 | 06B5F5B9 | 06B5F5B9 | 06B5F5B9
glass_lime | C6EEBF3A | C6EEBF3A | 4C49CD15 | 4C49CD15 | 4C49CD15
glass_magenta | 871486CE | 871486CE | 12315D6B | 12315D6B | 12315D6B
glass_orange | FF394E09 | FF394E09 | C3A0F807 | C3A0F807 | C3A0F807
glass_pink | F8BDD020 | F8BDD020 | 2CD1BDEE | 2CD1BDEE | 2CD1BDEE
glass_purple | A3EAF81D | A3EAF81D | C0CC9603 | C0CC9603 | C0CC9603
glass_red | 45CD63C1 | 45CD63C1 | 6293547D | 6293547D | 6293547D
glass_silver | 1F3A1C0A | 1F3A1C0A | 5C7F8AF3 | 5C7F8AF3 | 5C7F8AF3
glass_white | 1C366B0A | 1C366B0A | 8B8E2D02 | 8B8E2D02 | 57403861
glass_yellow | D091E096 | D091E096 | F3C4CE7B | F3C4CE7B | F3C4CE7B
glass_pane_top | 7017C8A2 | 7017C8A2 | 7017C8A2 | 7017C8A2 | 7017C8A2
glass_pane_top_black | 347A1EC6 | 347A1EC6 | 347A1EC6 | 347A1EC6 | 347A1EC6
glass_pane_top_blue | 3A098A17 | 3A098A17 | 3A098A17 | 3A098A17 | 3A098A17
glass_pane_top_brown | A7D749E0 | A7D749E0 | A7D749E0 | A7D749E0 | A7D749E0
glass_pane_top_cyan | 47B1E71E | 47B1E71E | 47B1E71E | 47B1E71E | 47B1E71E
glass_pane_top_gray | D67F2E9F | D67F2E9F | D67F2E9F | D67F2E9F | D67F2E9F
glass_pane_top_green | 25038879 | 25038879 | 25038879 | 25038879 | 25038879
glass_pane_top_light_blue | 09FB500E | 09FB500E | 09FB500E | 09FB500E | 09FB500E
glass_pane_top_lime | 9B6A4E50 | 9B6A4E50 | 9B6A4E50 | 9B6A4E50 | 9B6A4E50
glass_pane_top_magenta | C5F6F26E | C5F6F26E | C5F6F26E | C5F6F26E | C5F6F26E
glass_pane_top_orange | F769C419 | F769C419 | F769C419 | F769C419 | F769C419
glass_pane_top_pink | DD4F8413 | DD4F8413 | DD4F8413 | DD4F8413 | DD4F8413
glass_pane_top_purple | 5970EE20 | 5970EE20 | 5970EE20 | 5970EE20 | 5970EE20
glass_pane_top_red | BCD5C402 | BCD5C402 | BCD5C402 | BCD5C402 | BCD5C402
glass_pane_top_silver | CEE78F87 | CEE78F87 | CEE78F87 | CEE78F87 | CEE78F87
glass_pane_top_white | 23656ED6 | 23656ED6 | 8863E33B | 8863E33B | 02A8577F
glass_pane_top_yellow | 896A5C51 | 896A5C51 | 896A5C51 | 896A5C51 | 896A5C51
