### ISSUE TITLE
Unused Textures

### ISSUE THREAD

**Issue by EltrutLikes** [FaithfulTeam/Faithful#14]
There are many textures in this resource pack that **aren't even used by Minecraft.** Why are these textures here?

These textures are:
- **blocks/debug**
- **blocks/debug_2**
- **blocks/shulker_top_...** (entity/shulker/... are used instead)
- **effect/dither**
- **entity/arrow** (entity/projectiles/arrow used instead)
- **entity/boat** (entity/boat/boat_oak used instead)
- **items/bed** (unused since 1.12)
- **items/quiver**
- **items/ruby**

**Comment by xMrVizzy** [comment]
because this textures contains in vanilla textures folder

**Comment by EltrutLikes** [comment]
@xMrVizzy Ok sure, but still:

- the **effect/dither** in Faithful Vanilla is the **exact** same thing as the one in the Vanilla resource pack
- **entity/boat** is not in the vanilla textures folder
- **items/bed** is not in vanilla textures folder
- **items/quiver** is not in vanilla textures folder

If you're not going to do anything about the other unused textures, at least get rid of those.

**Comment by xMrVizzy** [comment]
kk thx
