### ISSUE TITLE
Nordic letters broken in 1.14-r3&s14

### ISSUE THREAD

**Issue by jonassm** [FaithfulTeam/Faithful#31]
Hi,

I use a nordic keyboard, and since 1.14 the "ø æ å" letters have been broken.
Pictured is a sign with said letters with faithful on and off(default). Left is lowercase and right is uppercase.
It appears as if the texture itself is simply just extremely large. Looking at the uppercase Å Ø Æ, it looks like its the right one.
I'm sorry if this is a Minecraft issue, but since it disappears when using default i thought to put this here.

![2019-05-31_16 50 58](https://user-images.githubusercontent.com/708819/58714133-630aed80-83c4-11e9-985e-388cfaf6e883.png)
![2019-05-31_16 51 06](https://user-images.githubusercontent.com/708819/58714134-63a38400-83c4-11e9-959a-814f254fc64f.png)

**Comment by DebexeL** [comment]
Same here, works fine on minecraft 1.14.2 default resource pack, but when using Faithful, they are broken.
If you force Unicode font, however, they work normally.
Previously mentioned letters ø æ å and also ä ö are broken and if you use uppercase they are visible, but bigger font size than other non-nordic letters in uppercase.

**Comment by xMrVizzy** [comment]
@DebexeL Okay I will fix it

**Comment by orblazer** [comment]
This is same for french accent

I have write : `&é"'(-è_çà)=`
![2019-07-26_10 44 45](https://user-images.githubusercontent.com/1344792/61938968-8dc38d80-af92-11e9-80d9-20f6c03b99ea.png)

**Comment by 0x9fff00** [comment]
Same issue on 1.14.4-r1, both lower and upper case `åäöÅÄÖ` are further down than other characters.

Faithful:
![2019-08-06_18 05 06](https://user-images.githubusercontent.com/10777601/62556509-521fa200-b875-11e9-8f27-18f2ac395505.png)
Default:
![2019-08-06_18 05 30](https://user-images.githubusercontent.com/10777601/62556536-61065480-b875-11e9-8849-6adfc6fa14cf.png)

**Comment by BigB00st** [comment]
The same is for Hebrew, it displays wierd symbols.
