### ISSUE TITLE
Add support for connected textures

### ISSUE THREAD

**Issue by Genhis** [FaithfulTeam/Faithful#33]
Hi,

Can you make glass (and other textures) compatible with Optifine's connected textures? Or is there an addon which does that?

**Comment by parmort** [comment]
[Faithful-CTM.zip](https://github.com/FaithfulTeam/Faithful/files/3427744/Faithful-CTM.zip)
Here's something I cooked up. Just put it on top of Faithful and it should work. This is not an official pack or anything, just something I did by myself.

**Comment by xMrVizzy** [comment]
Done
