### ISSUE TITLE
Banners and Shields: minecraft/textures/entity/banner/gradient.png

### ISSUE THREAD

**Issue by InfamousMusicify** [FaithfulTeam/Faithful#43]
Version 1.15-r1
gradient.png in particular and gradient_up.png seem to be displaying incorrectly,  I'm getting a solid color instead of a gradient.

this is also true of shields with banners applied.
minecraft/textures/entity/shield

**Comment by xMrVizzy** [comment]
@InfamousMusicify Yes, that’s hard to port old banners pattern to new system, because old ones was not transparent like new. I plan to fully remake all patterns

**Comment by InfamousMusicify** [comment]
<3 <3 <3 
Thank you for the quick response lol.  I figured it was so.  I look to the fresh Patterns!  Keep up the stunning work! <3

**Comment by InfamousMusicify** [comment]
so by deleting "gradient_up.png" the banner i was looking at now looks normal as ever.
at least for banners that is a minor solution.  I can see that shields is still in Dev mode.
(I am using the 1.14 block textures because I prefer them and antvenoms gui, so i made my own little pack, hope this info helps other folks in a similar situation.(if they somehow manage to find it with google-foo.))

**Comment by Nekzuris** [comment]
I have converted all banner and shield patterns from Faithful 1.14 to the new 1.15 format like 2 months ago and I posted them in the Faithful discord, don't know if you saw them ^^
[Banners Fix 1.15.zip](https://github.com/FaithfulTeam/Faithful/files/4097802/Banners.Fix.1.15.zip)

My texture work perfectly, however it's just a conversion from 1.14 and I didn't really like them so if you plan to remake them entirely than nice.

**Comment by InfamousMusicify** [comment]
Ah thank you for the link <3 I was not in the discord I shall hop in there.

**Comment by xMrVizzy** [comment]
Oh okay, will fix in new update!

**Comment by Nekzuris** [comment]
Yeah I what talking to @xMrVizzy for the discord.

**Comment by LukasAppleFan** [comment]
> I have converted all banner and shield patterns from Faithful 1.14 to the new 1.15 format like 2 months ago and I posted them in the Faithful discord, don't know if you saw them ^^
> [Banners Fix 1.15.zip](https://github.com/FaithfulTeam/Faithful/files/4097802/Banners.Fix.1.15.zip)
> 
> My texture work perfectly, however it's just a conversion from 1.14 and I didn't really like them so if you plan to remake them entirely than nice.

Just so you now, it is still working as of today, I don't know if the pack has received updates but it is still useful, thanks guys !

**Comment by Nekzuris** [comment]
Dude what are you doing @xMrVizzy ?
If you doesn't like my texture make your own because it's been like 6 month and Faithful still doesn't support new banner & shield format...

**Comment by LukasAppleFan** [comment]
@Nekzuris at least you have a fix, and do you have unicode glitch as well ?

**Comment by Nekzuris** [comment]
Yep that's because minecraft doesn't support HD unicode font (at least the way it's in Faithful, with the 512px texture)
So the simple fix for the moment is to delete all texture named `unicode_page_XX.png` in `assets/minecraft/textures/font/`
