### ISSUE TITLE
Faithful resizes JEI GUI but does not resize page selector

### ISSUE THREAD

**Issue by JonathanxD** [FaithfulTeam/Faithful#5]
Faithful resizes JEI GUI but does not resize page selector.

Minecraft 1.11.2
Faithful: 1.11.2-rv4

Screenshots:
854x480: ![2017-04-18_21 13 36](https://cloud.githubusercontent.com/assets/5360060/25158535/ad22f10c-247f-11e7-82ab-4eaba785513f.png)
1680x1050: ![2017-04-18_21 13 39](https://cloud.githubusercontent.com/assets/5360060/25158536/b85fbe88-247f-11e7-9d7d-57bfa2722588.png)

[JEI Issue](https://github.com/mezz/JustEnoughItems/issues/823)

**Comment by xMrVizzy** [comment]
At First it's not Faithful bug, you should open this issue in Faithful Mods repository, and In second it's bug because JEI update so quickly and in other new version mezz change GUI
