### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by JuniorJPDJ** [FaithfulTeam/Faithful#51]
Hi guys,
Firstly - thank you very much for your amazing work!
My team needs some textures for our project, your pack seems to satisfy our needs at least good but you haven't declared any license.
Could you please specify license which your work use?
There's web page which may help you choose good one: https://choosealicense.com/

**Comment by xMrVizzy** [comment]
Yes, soon will add it! Thank you!

**Comment by samscode** [comment]
Is it ok to use these textures in mods for other games?

**Comment by xMrVizzy** [comment]
you can pick some textures in mods, but not all!

**Comment by SnarkBoojum** [comment]
I confirm the License question : some textures have been used elsewhere, I know they come from here, but I have no clue if I can use/distribute them in turn, since I don't know what the original license is!

**Comment by samscode** [comment]
Could I ask that someone selects a reasonable license on behalf of all contributors in the meantime but then also ask all contributors to accept the choice or notify otherwise? It's possible to change license terms later if need be. The way Copyright generally works, everyone will need to comply with the new license or stop using the content. The old license becomes void. I wouldn't recommend going with a non-attribution license in these circumstances because it would be very hard to trace any derived works that need to cease distribution or be amended to comply with any new terms.

**Comment by SnarkBoojum** [comment]
No, as far as I know, if there is a clear old license, people who had the file can still use the old license. And if there was no clear license, people just had no right.

We need a clear license to get the rights (use, distribute, etc...)

**Comment by samscode** [comment]
My understanding is that at the end of the day, most jurisdictions will uphold the rights of the copyright holder regardless of any opensource license that might have been issued along with their works. But it's going to depend a lot on the situation. Unless money has changed hands, it's unlikely that someone using the work is going to have any rights in court vs. the actual copyright holder. These licenses are more for us to feel somewhat satisfied that the copyright holders aren't going to take us to court, or more likely, ask us to stop using them under threat of legal action. Just pick something, I'm happy to stop using the content if the license terms change.

**Comment by samscode** [comment]
Or indeed, include the fact that the license terms are indicative and subject to change upon agreement of all contributors.

**Comment by webketje** [comment]
Hi I have a similar question: I would like to create a webtool similar to https://mcdesign.michd.me/ but more advanced (to allow multi-layer structure planning), and was wondering whether, - given attribution & backlink to Faithful.team in the footer -, the Faithful textures could be used for this purpose. In effect, I would like to use it under conditions of a [Creative Commons Attribution-ShareAlike license](https://creativecommons.org/licenses/by-sa/4.0/), can that be done?

**Comment by seirin-blu** [comment]
Unfortunately, no. Although we don't have a license on this page (for some reason). On our discord server there is what kinds equates to one. Distributing unaltered textures falls within what it prohibits. Sorry. Unless you obtain a Yes from Vizzy.

**Comment by webketje** [comment]
@seirin-blu thank you for the quick reply, I'll check out the Discord. If you happen to come across a resource pack which does allow re-use for non-commercial purpose and redistribution as a derivative that is not a resource pack, if given attribution, it would be highly appreciated if you could report back.
