### ISSUE TITLE
2 Pixels missing on heart icon of the health bar

### ISSUE THREAD

**Issue by Catoryu** [FaithfulTeam/Faithful#59]
On file **\assets\minecraft\textures\gui\icons.png**, the heart container should look like this to be more clean :
![image](https://user-images.githubusercontent.com/34058720/81994522-5a004400-9648-11ea-8a58-63f65dde5c36.png)

**Comment by xMrVizzy** [comment]
Yes, icons should be updated, I will add it. Thanks!
