### ISSUE TITLE
Okay to download your pack from texture-packs.com?

### ISSUE THREAD

**Issue by pcunite** [FaithfulTeam/Faithful#66]
I found, what appears to be your pack from texture-packs.com. Is [this your](https://texture-packs.com/mcpe/faithful/) pack?

**Comment by seirin-blu** [comment]
This was most likely not authorized. DMCA takedown time

**Comment by h3oCharles** [comment]
no, [faithful.team](https://faithful.team/) should be the only way

**Comment by RobertRR11** [comment]
No, https://faithful.team/ is the only site which officially provides the Faithful 32x resource pack.
Any other site may be unsafe or distribute unallowed copies.

**Comment by pcunite** [comment]
Okay. I've been using Vattic's pack for a long time. Went looking the other day and became confused as to who is the correct owner. I think the faithful website needs to be updated with how things have changed and some history information under an _About_ section. Also, please release a **mcpack** file. When I purchased through the marketplace, I was not able to load the pack on my children's computers. Is there a way to do this? Surely I don't need to buy the pack three times?

**Comment by seirin-blu** [comment]
Is the game the Java Edition or Windows 10 edition?

**Comment by pcunite** [comment]
> 
> 
> Is the game the Java Edition or Windows 10 edition?


Windows 10, Bedrock

**Comment by seirin-blu** [comment]
If you've downloaded it from the marketplace you should be able to go into minecrafts settings, go to global resources, then enable it.

**Comment by pcunite** [comment]
> 
> 
> go into minecrafts settings, go to global resources, then enable it.

Yes, that is working fine on the first PC. I'm asking about _installing for the whole family_, each with their own computer and Minecraft accounts. This is where the **mcpack** is handy. I can copy it to the _resource_packs_ folder and be good to go. Please make a way to buy it this way as opposed to the restrictive _marketplace_.

**Comment by seirin-blu** [comment]
I unfortunately don't have control over that, (I'll talk to the person who does), but for the time being, use [this](https://github.com/seirin-blu/Faithful_BE_addons/raw/master/Faithful-1.16.1.mcpack). It doesn't contain all of the UI, but it does have all of the blocks, items, and works on Bedrock. As for installation through Window's file manager, you'll have to look that up as I don't know how.

**Comment by pcunite** [comment]
> 
> 
> installation through Window's file manager, you'll have to look that up as I don't know how.

Works great! All that needs to be done is copy it to the _LocalState\games\com.mojang\resource_packs_ folder, then start Minecraft. It will be then be visible under _Global Resources/My Packs_ menu.

Thank you so much.

**Comment by MaxBr5** [comment]
Vizzy doesn't own the copyright. Vattic does and the one you should get is compliance.

**Comment by MaxBr5** [comment]
Vizzy is a theif.

**Comment by MaxBr5** [comment]
No DMCA takedown on the name of Vattic and the fact that Vizzy is a theif.

**Comment by MaxBr5** [comment]
get it from https://github.com/EmulatedVattic/EM32D for Vattic's original style or from https://compliancepack.net/  fploaded with vattic's permission. Faithfulteam.net is pirated.

**Comment by MaxBr5** [comment]
faithful.team is pirated.
