### ISSUE TITLE
The `pack_format` in `pack.mcmeta` will need to change in 1.16.2 (otherwise it's "Incompatible")

### ISSUE THREAD

**Issue by MartyMacGyver** [FaithfulTeam/Faithful#69]
FYI, in MC 1.16.2 the `pack_format` value is `6`. I'm not sure what's actually different about it though, besides the number

https://bugs.mojang.com/browse/MC-197355

https://minecraft.gamepedia.com/Resource_Pack#Contents

**Comment by seirin-blu** [comment]
Thanks. I've made a pull request that includes this along with a lot of other things that need to be added.

**Comment by MartyMacGyver** [comment]
> Thanks. I've made a pull request that includes this along with a lot of other things that need to be added.

It looks like this and everything else through your 7762dc1 commit was in today's 1.16.2 release.

Shame about the `master` branch, but it doesn't look like you lost anything you couldn't quickly replace (I hope that's right anyway).

Thanks again for all the work getting things up-to-date!
