### ISSUE TITLE
Outdated Squid texture

### ISSUE THREAD

**Issue by ghost** [FaithfulTeam/Faithful#73]
The squid texture looks outdated, if you could change it to be more fitting to the new 1.14 textures
![squid](https://user-images.githubusercontent.com/72634275/95641450-491cf880-0a57-11eb-9055-dec1fdb354d2.png)

**Comment by MaxBr5** [comment]
For this texture is from the era of the real vattic.

**Comment by MaxBr5** [comment]
Not the phoeny that is Vizzy.
