### ISSUE TITLE
Missing banner patterns when applied on a shield

### ISSUE THREAD

**Issue by NatoBoram** [FaithfulTeam/Faithful#74]
![Error](https://cdn.discordapp.com/attachments/743969620884717569/801261709494059008/unknown.png)

![](https://cdn.discordapp.com/attachments/161636856482496522/801262075405795328/unknown.png)

Pattern : https://minecraft.tools/en/banner.php?color_id_0=12&shape_id_1=36&color_id_1=4&shape_id_2=21&color_id_2=0&shape_id_3=22&color_id_3=0&shape_id_4=1&color_id_4=13&shape_id_5=20&color_id_5=0&shape_id_6=25&color_id_6=0#crafting

**Comment by ghost** [comment]
Same issue here, only the last pattern applied renders.
