### ISSUE TITLE
Some characters with accent are not working properly

### ISSUE THREAD

**Issue by LukasMFR** [FaithfulTeam/Faithful#76]
Hello,
I downloaded the official 1.16.zip from the website but it turns out that some characters like é, è and others are not "faithful" but they use the default minecraft textures.
I also have another file called Faithful-1.16.3.zip which does have those characters working properly in x32.
Thanks

**Comment by el97** [comment]
I am experiencing the same issue. Looks like it effects several letters such as the Swedish vowels åäö
