### ISSUE TITLE
The fish bucket in 1.17 is wrong

### ISSUE THREAD

**Issue by OMSociety** [FaithfulTeam/Faithful#79]
It‘s different from other bucket.
I draw some new ones,if you think they are right,please use
![cod_bucket](https://user-images.githubusercontent.com/85862362/123550517-6f7af380-d7a0-11eb-9aab-5b8c85b6a2b9.png)
 
![pufferfish_bucket](https://user-images.githubusercontent.com/85862362/123550518-70138a00-d7a0-11eb-8a74-c3fcb97ae7fe.png)
![QQ图片20210627233541](https://user-images.githubusercontent.com/85862362/123550520-70ac2080-d7a0-11eb-8fc0-7442056e1e1a.png)
![salmon_bucket](https://user-images.githubusercontent.com/85862362/123550521-70ac2080-d7a0-11eb-821f-9a44d5655906.png)

> 
![tropical_fish_bucket](https://user-images.githubusercontent.com/85862362/123550514-6db13000-d7a0-11eb-8c90-0b2f7b2e6fe7.png)

**Comment by MaxBr5** [comment]
good thing
