### ISSUE TITLE
Broken Characters since 1.17.1

### ISSUE THREAD

**Issue by Brokkonaut** [FaithfulTeam/Faithful#82]
Since Minecraft 1.17.1 some characters, for example the german ß are incorrectly displayed.

**Comment by GriffinCodes** [comment]
Some emojis are broken as well, such as ⚡, ✔, and ❤
![image](https://user-images.githubusercontent.com/12417961/127164270-685cd61a-f060-4ebe-b83d-6da679ccaa85.png)

**Comment by Angelic-System** [comment]
Yeah its a font bug

**Comment by Blyrexx** [comment]
The font bug got fixed
![Screenshot](https://user-images.githubusercontent.com/58655519/138585540-79974136-cc09-4876-8c30-83d62d13a1be.png)
