### ISSUE TITLE
Stone Bricks Missing

### ISSUE THREAD

**Issue by nullagit** [FaithfulTeam/Faithful#84]
Stone Bricks are rendering with a red texture. Looks like terracotta? 

![Missing Stone Bricks](https://i.imgur.com/FA89rlZ.png)

**Comment by nullagit** [comment]
1.17.1 forge/optifine.

**Comment by Blyrexx** [comment]
Stone Bricks textures are working fine for me with 1.17.1
![Screenshot](https://i.imgur.com/180Ct51.png)

**Comment by nullagit** [comment]
Yes, I should have mentioned it's intermittent. It's usually right when I load the world and pressing F3 + T to reload textures fixes it.
