### ISSUE TITLE
Take this down.

### ISSUE THREAD

**Issue by qewrwer23qf** [FaithfulTeam/Faithful#89]
Take this down.

**Comment by MaxBr5** [comment]
<pre>Maybe not take this down but you should credit Vattic
and take it off the market place and rename it for Vattic's
sake. Vattic is the original creator ans should be credited
and Vattic never gave you the rights to sell it. Let alone
just calling it faithfull. Refund the marketplace customers too.</pre>
#88

**Comment by ghost** [comment]
🤡
