### ISSUE TITLE
Hopper ToolTip / Dropped

### ISSUE THREAD

**Issue by dg01d** [FaithfulTeam/Faithful#9]
Hi,

Faithful 1.12 appears to have regression in appearance of hoppers in the menu and in the dropped item. 1.11 had the 'squared' appearance in both cases, while 1.12 has what appears to be an unaltered 'cone'.

**Comment by EltrutLikes** [comment]
He removed the item models in a commit a while back: b8defde038dd84dd522e20d884fb82edd074f701

It's probably because the hopper and the cauldron were the only two items who had this feature, so it was kind of lacking.

**Comment by EltrutLikes** [comment]
I think this is intentional, and if it is, could @xMrVizzy please close this?
