### ISSUE TITLE
question: why did vattic disappear?

### ISSUE THREAD

**Issue by afkvido** [FaithfulTeam/Faithful#93]
what happened to vattic?

**Comment by Enxivity** [comment]
Watch antvenoms video on faithful pack

**Comment by afkvido** [comment]
> Watch antvenoms video on faithful pack

Ok, I will.

edit: it doesn't say exactly what happened to vattic.

**Comment by MacStevins** [comment]
> it doesn't say exactly what happened to vattic.

Well Ant said its personal details, so he didn't say what happened

**Comment by afkvido** [comment]
Exactly. I'd like to know the "personal details".

**Comment by MacStevins** [comment]
> Exactly. I'd like to know the "personal details".

If you want to know the "personal details", ask Vattic himself, but he wants to keep that to himself and people that he trust. If you persist him to get that, you might be a creep.

**Comment by afkvido** [comment]
How do I contact Vattic?

**Comment by MacStevins** [comment]
> If you persist him to get that, you might be a creep.

Please put this in mind, even tho you havent contacted him.

**Comment by afkvido** [comment]
I'm not persisting... I'm just asking, if he doesn't want to share anything then I can't do anything.

**Comment by afkvido** [comment]
@Kraineff do you know what happened to Vattic?

**Comment by FHLX-J** [comment]
> @Kraineff do you know what happened to Vattic?

He doesn't know, but I know. I haven't contacted him a while, there hasn't been a reason to, but he's probably fine. Just a reserved guy overall so he isn't the most public.
